name:           lab1
version:        0.1.0.0
description:    Project Euler Solutions for Functional Programming Course

dependencies:
  - base >= 4.7

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Werror

library:
  source-dirs: src

tests:
  lab1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lab1
      - hspec
      - QuickCheck